<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shadowRootParentElement</name>
   <tag></tag>
   <elementGuidId>c51bfd6f-e85b-4a2e-91eb-432318c1226f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>hydra-claw</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>hydra-claw</value>
      <webElementGuid>9e7ba3ee-1e2c-4481-879b-60ed3067e9d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
